# server:
#   port: 8081

# spring:
#   jackson:
#     property-naming-strategy: SNAKE_CASE
#   devtools:
#     livereload:
#       enabled: true
#   datasource:
#     url: jdbc:oracle:thin:@192.168.0.50:1521:PDSYS
#     username: pd_insa
#     password: pd_insa
#     driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
#   devtools:
#     livereload:
#       enabled: true
#   datasource:
#     url: jdbc:oracle:thin:@192.168.0.50:1521:PDSYS
#     username: pd_insa
#     password: pd_insa
#     driver-class-name: oracle.jdbc.driver.OracleDriver
  # datasource:
  #   url: jdbc:oracle:thin:@LOCALHOST:1521:XE
  #   username: system 
  #   password: system
  #   driver-class-name: oracle.jdbc.driver.OracleDriver
