# server:
#   port: 8081

# spring:
#   jackson:
#     property-naming-strategy: SNAKE_CASE
#   devtools:
#     livereload:
#       enabled: true
#   datasource:
#     url: jdbc:oracle:thin:@192.168.0.50:1521:PDSYS
#     username: pd_insa
#     password: pd_insa
#     driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    # hibernate:
    #   ddl-auto: create
    open-in-view: false
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@192.168.0.50:1521:PDSYS
    username: TS_USER
    password: TS_USER
    driver-class-name: oracle.jdbc.driver.OracleDriver
  # datasource:
  #   url: jdbc:oracle:thin:@LOCALHOST:1521:XE
  #   username: system 
  #   password: system
  #   driver-class-name: oracle.jdbc.driver.OracleDriver
